"""
ACDA-SDK — Agent Code Generator
Compiles validated AgentDefinition objects into production Python microservice code.
Uses Jinja2 templates to emit fully typed, async, runtime-integrated agent classes.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Optional

from jinja2 import Environment, BaseLoader

from acda.models.schemas import AgentDefinition


# ─────────────────────────────────────────────
# Jinja2 Template
# ─────────────────────────────────────────────

AGENT_TEMPLATE = '''\
"""
AUTO-GENERATED by ACDA-SDK Agent Compiler
Agent  : {{ agent.name }}
Version: {{ agent.version }}
Task   : {{ agent.reasoning.task if agent.reasoning else "N/A" }}

DO NOT EDIT — regenerate via: acda build {{ definition_path }}
"""

from __future__ import annotations

import asyncio
import time
import uuid
from typing import Any, Dict, List, Optional

from acda.runtime.base_agent import BaseAgent, AgentContext
from acda.runtime.data_collector import DataCollector
from acda.runtime.reasoning_engine import ReasoningEngine
from acda.runtime.consensus_validator import ConsensusValidator
from acda.runtime.action_executor import ActionExecutor
from acda.models.schemas import (
    SecurityEvent, CollectedData, ReasoningResult,
    ConsensusResult, AgentExecutionReport, ActionResult,
)
import structlog

logger = structlog.get_logger(__name__)


class {{ agent.name }}(BaseAgent):
    """
    {{ agent.metadata.description }}

    Priority  : {{ agent.metadata.priority }}
    Owner     : {{ agent.metadata.owner }}
    Version   : {{ agent.version }}
    """

    # ── Trigger configuration ──────────────────────────────────
    TRIGGERS: List[str] = {{ trigger_list }}
    {% if schedule_interval %}
    SCHEDULE_INTERVAL: str = "{{ schedule_interval }}"
    {% endif %}

    # ── Data collection ────────────────────────────────────────
    DATA_SOURCES: List[str] = {{ sources_list }}
    TIME_WINDOW: str = "{{ time_window }}"

    # ── Reasoning ─────────────────────────────────────────────
    {% if agent.reasoning %}
    AI_MODELS: List[str] = {{ ai_models_list }}
    REASONING_TASK: str = "{{ agent.reasoning.task }}"
    REASONING_TEMPERATURE: float = {{ agent.reasoning.temperature }}
    {% else %}
    AI_MODELS: List[str] = []
    REASONING_TASK: str = "none"
    REASONING_TEMPERATURE: float = 0.0
    {% endif %}

    # ── Consensus ─────────────────────────────────────────────
    {% if agent.consensus_validation %}
    # FIX: Use consensus_method_value (the plain string) not the enum repr.
    CONSENSUS_METHOD: str = "{{ consensus_method_value }}"
    CONSENSUS_THRESHOLD: float = {{ agent.consensus_validation.threshold }}
    CONSENSUS_WEIGHTS: Dict[str, float] = {{ consensus_weights }}
    {% else %}
    CONSENSUS_METHOD: str = "none"
    CONSENSUS_THRESHOLD: float = 1.0
    CONSENSUS_WEIGHTS: Dict[str, float] = {}
    {% endif %}

    # ── Actions ───────────────────────────────────────────────
    ACTIONS: List[str] = {{ actions_list }}

    # ── Safety controls ───────────────────────────────────────
    MAX_RUNTIME: str = "{{ agent.safety_controls.max_runtime }}"
    APPROVAL_REQUIRED: str = "{{ agent.safety_controls.approval_required or 'none' }}"
    DRY_RUN_MODE: bool = {{ "True" if agent.safety_controls.dry_run_mode else "False" }}
    ESCALATION_REQUIRED: bool = {{ "True" if agent.safety_controls.escalation_required else "False" }}

    # ─────────────────────────────────────────────────────────
    def __init__(self) -> None:
        super().__init__(
            name="{{ agent.name }}",
            version="{{ agent.version }}",
        )
        self._collector = DataCollector(
            sources=self.DATA_SOURCES,
            time_window=self.TIME_WINDOW,
        )
        {% if agent.reasoning %}
        self._reasoner = ReasoningEngine(
            models=self.AI_MODELS,
            task=self.REASONING_TASK,
            temperature=self.REASONING_TEMPERATURE,
        )
        {% endif %}
        {% if agent.consensus_validation %}
        self._consensus = ConsensusValidator(
            method=self.CONSENSUS_METHOD,
            threshold=self.CONSENSUS_THRESHOLD,
            weights=self.CONSENSUS_WEIGHTS,
        )
        {% endif %}
        self._executor = ActionExecutor(
            actions=self.ACTIONS,
            approval_required=self.APPROVAL_REQUIRED,
            dry_run=self.DRY_RUN_MODE,
        )

    # ─────────────────────────────────────────────────────────
    async def collect_data(self, event: SecurityEvent) -> CollectedData:
        """
        Collect all relevant security telemetry for this event.
        Sources: {{ sources_list }}
        Window : {{ time_window }}
        """
        logger.info(
            "collecting_data",
            agent="{{ agent.name }}",
            event_id=event.event_id,
            event_type=event.event_type,
            sources=self.DATA_SOURCES,
        )
        start = time.perf_counter()
        data = await self._collector.collect(event)
        data.collection_time_ms = (time.perf_counter() - start) * 1000
        logger.info(
            "data_collected",
            agent="{{ agent.name }}",
            records=len(data.logs),
            duration_ms=round(data.collection_time_ms, 2),
        )
        return data

    # ─────────────────────────────────────────────────────────
    {% if agent.reasoning %}
    async def analyze(self, data: CollectedData) -> ReasoningResult:
        """
        Run multi-model AI analysis.
        Task  : {{ agent.reasoning.task }}
        Models: {{ ai_models_list }}
        """
        logger.info(
            "starting_analysis",
            agent="{{ agent.name }}",
            task=self.REASONING_TASK,
            models=self.AI_MODELS,
        )
        result = await self._reasoner.run(data)
        logger.info(
            "analysis_complete",
            agent="{{ agent.name }}",
            model_count=len(result.scores),
        )
        return result

    {% endif %}
    # ─────────────────────────────────────────────────────────
    {% if agent.consensus_validation %}
    async def validate_consensus(self, reasoning: ReasoningResult) -> ConsensusResult:
        """
        Validate AI decisions via consensus.
        Method   : {{ consensus_method_value }}
        Threshold: {{ agent.consensus_validation.threshold }}
        """
        logger.info(
            "validating_consensus",
            agent="{{ agent.name }}",
            method=self.CONSENSUS_METHOD,
            threshold=self.CONSENSUS_THRESHOLD,
        )
        result = await self._consensus.validate(reasoning)
        logger.info(
            "consensus_result",
            agent="{{ agent.name }}",
            passed=result.passed,
            score=round(result.score, 4),
        )
        return result

    {% endif %}
    # ─────────────────────────────────────────────────────────
    async def execute_actions(
        self,
        event: SecurityEvent,
        consensus: Optional[ConsensusResult] = None,
    ) -> List[ActionResult]:
        """
        Execute defense actions.
        Actions: {{ actions_list }}
        """
        {% if agent.consensus_validation %}
        if consensus is None or not consensus.passed:
            logger.warning(
                "actions_blocked_by_consensus",
                agent="{{ agent.name }}",
                event_id=event.event_id,
                score=consensus.score if consensus else 0.0,
                threshold=self.CONSENSUS_THRESHOLD,
            )
            return []
        {% endif %}

        logger.info(
            "executing_actions",
            agent="{{ agent.name }}",
            actions=self.ACTIONS,
            dry_run=self.DRY_RUN_MODE,
        )
        results = await self._executor.run(event, self.ACTIONS)
        for r in results:
            logger.info(
                "action_result",
                agent="{{ agent.name }}",
                action=r.action,
                success=r.success,
                dry_run=r.dry_run,
            )
        return results

    # ─────────────────────────────────────────────────────────
    async def run(self, event: SecurityEvent) -> AgentExecutionReport:
        """
        Full agent execution lifecycle:
          1. Collect data
          2. AI reasoning
          3. Consensus validation
          4. Execute defense actions
        """
        execution_id = str(uuid.uuid4())
        start = time.perf_counter()

        logger.info(
            "agent_execution_start",
            agent="{{ agent.name }}",
            execution_id=execution_id,
            event_id=event.event_id,
        )

        report = AgentExecutionReport(
            agent_name="{{ agent.name }}",
            execution_id=execution_id,
            event=event,
            data_collected=False,
        )

        try:
            # ── Step 1: Data Collection ────────────────────────
            data = await self.collect_data(event)
            report.data_collected = True

            # ── Step 2: AI Reasoning ──────────────────────────
            {% if agent.reasoning %}
            reasoning = await self.analyze(data)
            report.reasoning_result = reasoning
            {% else %}
            reasoning = None
            {% endif %}

            # ── Step 3: Consensus Validation ──────────────────
            {% if agent.consensus_validation %}
            consensus = await self.validate_consensus(reasoning)
            report.consensus_result = consensus
            {% else %}
            consensus = None
            {% endif %}

            # ── Step 4: Execute Actions ────────────────────────
            if self.ACTIONS:
                actions_taken = await self.execute_actions(event, consensus)
                report.actions_taken = actions_taken

            report.status = "completed"

        except asyncio.TimeoutError:
            report.status = "timeout"
            report.errors.append("Agent execution timed out.")
            logger.error("agent_timeout", agent="{{ agent.name }}", execution_id=execution_id)

        except Exception as exc:  # noqa: BLE001
            report.status = "error"
            report.errors.append(str(exc))
            logger.error(
                "agent_error",
                agent="{{ agent.name }}",
                execution_id=execution_id,
                error=str(exc),
                exc_info=True,
            )

        finally:
            report.duration_ms = (time.perf_counter() - start) * 1000
            logger.info(
                "agent_execution_end",
                agent="{{ agent.name }}",
                execution_id=execution_id,
                status=report.status,
                duration_ms=round(report.duration_ms, 2),
                actions=len(report.actions_taken),
            )

        return report
'''


# ─────────────────────────────────────────────
# Code Generator
# ─────────────────────────────────────────────


class AgentCodeGenerator:
    """
    Compiles a validated AgentDefinition into a production Python file.
    """

    def __init__(self) -> None:
        self._env = Environment(
            loader=BaseLoader(), trim_blocks=True, lstrip_blocks=True
        )
        self._template = self._env.from_string(AGENT_TEMPLATE)

    def generate(
        self,
        agent: AgentDefinition,
        definition_path: str = "agent.yaml",
        output_path: Optional[str | Path] = None,
    ) -> str:
        """Render the Jinja2 template and return the generated Python source."""

        # ── Derive trigger config ──
        triggers = agent.triggers.event_types or []
        trigger_list = repr(list(triggers))
        schedule_interval = (
            agent.triggers.schedule.interval if agent.triggers.schedule else None
        )

        # ── Derive data sources ──
        sources = agent.data_collection.sources or []
        sources_list = repr(list(sources))
        time_window = agent.data_collection.time_window

        # ── Derive reasoning ──
        ai_models_list = (
            repr(list(agent.reasoning.ai_models)) if agent.reasoning else repr([])
        )

        # ── FIX: Derive consensus method as plain string value ──
        # Previously the template used `{{ agent.consensus_validation.method }}`
        # which, with Pydantic v2's enum handling, could render as
        # "ConsensusMethod.WEIGHTED_VOTE" (the repr) instead of "weighted_vote"
        # (the value). This caused a ValueError in ConsensusValidator.__init__
        # when the generated agent was instantiated.
        if agent.consensus_validation:
            method_raw = agent.consensus_validation.method
            # Handle both enum objects and plain strings defensively
            consensus_method_value = (
                method_raw.value if hasattr(method_raw, "value") else str(method_raw)
            )
        else:
            consensus_method_value = "none"

        # ── Derive consensus weights ──
        if agent.consensus_validation and agent.consensus_validation.weights:
            consensus_weights = repr(dict(agent.consensus_validation.weights))
        elif agent.reasoning and agent.reasoning.ai_models:
            # Auto-assign equal weights
            n = len(agent.reasoning.ai_models)
            equal_w = round(1.0 / n, 4) if n else 0.0
            consensus_weights = repr({m: equal_w for m in agent.reasoning.ai_models})
        else:
            consensus_weights = repr({})

        # ── Derive actions ──
        actions_list = repr(list(agent.actions or []))

        context = {
            "agent": agent,
            "definition_path": definition_path,
            "trigger_list": trigger_list,
            "schedule_interval": schedule_interval,
            "sources_list": sources_list,
            "time_window": time_window,
            "ai_models_list": ai_models_list,
            "consensus_method_value": consensus_method_value,
            "consensus_weights": consensus_weights,
            "actions_list": actions_list,
        }

        code = self._template.render(**context)

        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(code, encoding="utf-8")

        return code

    def generate_from_file(
        self,
        definition_path: str | Path,
        output_dir: str | Path = "generated_agents",
    ) -> Path:
        """
        Convenience wrapper: validate YAML → generate Python → write to disk.
        Returns the path to the generated file.
        """
        import yaml
        from acda.compiler.schema_validator import AdfValidator
        from acda.models.schemas import AdfDocument

        definition_path = Path(definition_path)
        validator = AdfValidator()
        result, agent = validator.validate_file(definition_path)

        if not result.valid:
            result.print_report()
            raise ValueError(f"Validation failed for {definition_path}")

        assert agent is not None

        output_dir = Path(output_dir)
        output_file = output_dir / f"{agent.name.lower()}.py"

        self.generate(agent, str(definition_path), output_file)
        return output_file
